
export const AppIcons = {
	comment: '/light_icons/comment.png',
	back_arrow: '/light_icons/back_arrow.png',
	bookmarks_selected: '/light_icons/bookmarks_selected.png',
	bookmarks_default: '/light_icons/bookmarks_ default.png',
	calendar: '/light_icons/calendar.png',
	default_search: '/light_icons/default_search.png',
	ellipses_default: '/light_icons/ellipses_default.png',
	emoji: '/light_icons/emoji.png',
	explore_default: '/light_icons/explore_default.png',
	explore_selected: '/light_icons/explore_selected.png',
	gif: '/light_icons/gif.png',
	home_default: '/light_icons/home_default.png',
	like_default: '/light_icons/like_default.png',
	like_selected: '/light_icons/like_selected.png',
	lists_default: '/light_icons/lists_default.png',
	lists_selected: '/light_icons/lists_selected.png',
	location: '/light_icons/location.png',
	logo: '/light_icons/logo.png',
	media: '/light_icons/media.png',
	messages_default: '/light_icons/messages_default.png',
	messages_selected: '/light_icons/messages_selected.png',
	more: '/light_icons/more.png',
	notifications_selected: '/light_icons/notifications_selected.png',
	notifications_default: '/light_icons/notifications_default.png',
	poll: '/light_icons/poll.png',
	profile: '/light_icons/profile.png',
	profiles: '/light_icons/profiles.png',
	retweet: '/light_icons/retweet.png',
	schedule: '/light_icons/schedule.png',
	share: '/light_icons/share.png',
	top_tweet: '/light_icons/top_tweet.png',
	avatar_small: '/Avatar/avatarsmall.png',
	avatar_medium: '/Avatar/avatarmedium.png',
	media1: '/Feed/media1.png',
	media2: '/Feed/media2.png',
	media3: '/Feed/media3.png',
	user1: '/Feed/user1.png',
	user2: '/Feed/user2.png',
	tweet_p2: '/Feed/tweet_p2.png',
	post1: '/Feed/post.png',
	tweet_p: '/Feed/tweet_p.png',
	post2: '/Feed/post2.png',
	avatar_main: '/Feed/avatar_main.png',
	profile_background: '/Feed/profile_background.png',
};